### ISSUE TITLE
Question: smart_pytorch.py

### ISSUE THREAD

**Issue by kargaranamir** [archinetai/smart-pytorch#2]
Hi,
Thank you for the code. 

- I don't understand why we try to compute the new noise (Line 50 to 54). Since algorithm 1 in the paper, didn't do the same.
- Which parameter is the momentum parameter?

Thanks.

**Comment by flavioschneider** [comment]
Hi Amir! This algorithm is adapted from the [original implementation](https://github.com/namisan/mt-dnn/blob/master/mt_dnn/perturbation.py) to be usable on any model. It doesn't match exactly algorithm 1 in the paper as it perturbs directly the noise, instead of the entire embedding, but the principle should be similar. I was also a bit confused reading the mtdnn implementation. 

Currently, only the inner loop (S) is implemented, which provides the regularizer R_s, the momentum parameter is part of the Bregman proximal point update which should belong to the optimizer that I have not implemented. 

I still have to test this implementation, if it works I might try to reproduce the one in the paper to see if there are significant differences.

**Comment by kargaranamir** [comment]
Great! Thank you for your response.
